---
- hosts: all
  become: true
  gather_facts: no
  vars:
    contents: "{{ lookup('env','DOCKER_TAG') | replace('\n', '')}}"
  tasks:
    - name: remove stopped docker container
      shell: "ls -lrt"
      register: "output"
    - debug: var=output.stdout_lines