---
- hosts: all
  become: true
  gather_facts: no
  vars:
     contents: "{{ lookup('env','DOCKER_TAG') | replace('\n', '')}}"
  tasks:
  - name: stop if we have old docker container
    cmd: docker stop AnsibleContainer


  - name: remove stopped docker container
    cmd: docker rm AnsibleContainer


  - name: remove current docker image
    cmd: docker rmi -f $(docker images | grep mbreddy507/ansibledeploy)


  - debug: msg={{ contents }} 

  - name: creating docker image
    cmd: docker run -d -p 8050:8050 --name AnsibleContainer mbreddy507/ansibledeploy:"{{ contents }}"
