---
- hosts: localhost
  become: true
  gather_facts: no
  vars:
    contents: "{{ lookup('env','DOCKER_TAG') | replace('\n', '')}}"
  tasks:
    - name: remove stopped docker container
      command: docker ps -a